### ISSUE TITLE
OutOfMemoryError:

### ISSUE THREAD

**Issue by Edison0521** [queryproc/optimizing-subgraph-queries-combining-binary-and-worst-case-optimal-joins#4]
Hello, Thank you for the open-source code,but I try to set the JAVA_OPTS='-Xmx50G', but it seems doesn't work,Could you please help me to fix it?
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at ca.waterloo.dsg.graphflow.query.QueryGraph.addQEdgeToQGraph(QueryGraph.java:107)
	at ca.waterloo.dsg.graphflow.query.QueryGraph.addEdge(QueryGraph.java:95)
	at ca.waterloo.dsg.graphflow.query.QueryGraph$$Lambda$63/0x00000008001b7c40.accept(Unknown Source)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at ca.waterloo.dsg.graphflow.query.QueryGraph.addEdges(QueryGraph.java:53)
	at ca.waterloo.dsg.graphflow.query.QueryGraph.copy(QueryGraph.java:234)
	at ca.waterloo.dsg.graphflow.planner.catalog.CatalogPlans.setNoops(CatalogPlans.java:277)
	at ca.waterloo.dsg.graphflow.planner.catalog.CatalogPlans.setNextOperators(CatalogPlans.java:163)
	at ca.waterloo.dsg.graphflow.planner.catalog.CatalogPlans.setNextOperators(CatalogPlans.java:168)
	at ca.waterloo.dsg.graphflow.planner.catalog.Catalog.populate(Catalog.java:233)
	at ca.waterloo.dsg.graphflow.runner.dataset.CatalogSerializer.main(CatalogSerializer.java:62)

**Comment by queryproc** [comment]
Hello Edison!

I missed this issue. Is 50 GBs the largest amount of memory you have available?

**Comment by Edison0521** [comment]
> Hello Edison!
> 
> I missed this issue. Is 50 GBs the largest amount of memory you have available?

Yes,and I set by -Xmx500G
